services:
  peercoin-seeder-rust:
    build:
      context: .
      dockerfile: Dockerfile.builder
    container_name: peercoin-seeder-rust
    restart: always
    env_file:
      - .env
    ports:
      - "53:53/udp"
    command: >
      sh -c "peercoin-seeder-rust
      $${NETWORK_FLAG:---mainnet}
      --hostname $${HOSTNAME:-seed.peercoin.net}
      --nameserver $${NAMESERVER:-ns.peercoin.net}
      $${CRAWL_INTERVAL:+--crawl-interval $${CRAWL_INTERVAL}}
      $${VERBOSE_FLAG:-}"
    volumes:
      - "./data/:/data"
    cap_add:
      - NET_BIND_SERVICE
    healthcheck:
      test: ["CMD", "sh", "-c", "dig @127.0.0.1 $${HOSTNAME:-seed.peercoin.net} A"]
      interval: 300s
      timeout: 10s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: 100m  
      